/**
 * CURSOR READY — Export Utilities
 * Generates a single Markdown file with the complete project plan
 */

import { saveAs } from "file-saver";
import type { Locale } from "./i18n";
import { pipelineSteps } from "./pipeline";

export async function generateCursorPack(
  stepContent: Record<number, string>,
  locale: Locale
): Promise<void> {
  const projectName = "project-plan";
  const md = buildFullMarkdown(stepContent, locale);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, `${projectName}.md`);
}

function buildFullMarkdown(stepContent: Record<number, string>, locale: Locale): string {
  const isEn = locale === "en";
  const stepLabels = isEn
    ? ["Idea Clarifier", "PRD", "Features", "Architecture", "Database Schema", "API Spec", "Task Breakdown", "Coding Prompt"]
    : ["Klarifikasi Ide", "PRD", "Fitur", "Arsitektur", "Skema Database", "Spesifikasi API", "Rincian Tugas", "Prompt Coding"];

  let md = "";

  // Header
  md += `# ${isEn ? "Project Plan" : "Rencana Proyek"}\n\n`;
  md += `> ${isEn ? "Generated by Cursor Ready" : "Dihasilkan oleh Cursor Ready"}  \n`;
  md += `> ${new Date().toLocaleDateString(isEn ? "en-US" : "id-ID", { year: "numeric", month: "long", day: "numeric" })}\n\n`;
  md += `---\n\n`;

  // Table of Contents
  md += `## ${isEn ? "Table of Contents" : "Daftar Isi"}\n\n`;
  stepLabels.forEach((label, i) => {
    if (stepContent[i]) {
      md += `${i + 1}. [${label}](#${label.toLowerCase().replace(/\s+/g, "-")})\n`;
    }
  });
  md += `\n---\n\n`;

  // Each step as a section
  for (let i = 0; i < pipelineSteps.length; i++) {
    const content = stepContent[i];
    if (content) {
      md += `## ${stepLabels[i]}\n\n`;
      md += content.trim() + "\n\n";
      md += `---\n\n`;
    }
  }

  // Cursor Rules section (inline, not separate files)
  md += `## ${isEn ? "Cursor Rules" : "Aturan Cursor"}\n\n`;
  md += isEn
    ? `> Drop the rules below into \`.cursor/rules/project.mdc\` in your project root.\n\n`
    : `> Letakkan aturan di bawah ini ke \`.cursor/rules/project.mdc\` di root proyek Anda.\n\n`;
  md += "```yaml\n";
  md += `---\n`;
  md += `description: Project overview and conventions\n`;
  md += `globs: **/*\n`;
  md += `alwaysApply: true\n`;
  md += `---\n\n`;
  md += `# Project Overview\n\n`;
  md += `## Stack\n`;
  md += `- Next.js 15 (App Router)\n`;
  md += `- TypeScript (strict mode)\n`;
  md += `- Tailwind CSS\n`;
  md += `- Supabase (auth, database, storage)\n\n`;
  md += `## Conventions\n`;
  md += `- All components use PascalCase filenames\n`;
  md += `- API routes in /app/api/\n`;
  md += `- Shared types in /lib/types.ts\n`;
  md += `- No inline styles — Tailwind only\n`;
  md += `- Every function needs JSDoc comments\n`;
  md += `- Use Server Components by default\n`;
  md += "```\n\n";
  md += `---\n\n`;

  // Kickoff Prompt section
  md += `## ${isEn ? "Kickoff Prompt" : "Prompt Awal"}\n\n`;
  md += isEn
    ? `> Copy the prompt below and paste it into Cursor (or your preferred AI coding tool) to start building.\n\n`
    : `> Salin prompt di bawah ini dan tempel ke Cursor (atau tool coding AI pilihan Anda) untuk mulai membangun.\n\n`;
  md += "```\n";
  md += isEn
    ? `You are building a new web application. Read the project plan above for full context.\n\n`
    : `Anda membangun aplikasi web baru. Baca rencana proyek di atas untuk konteks lengkap.\n\n`;
  md += isEn
    ? `## Current Task: Phase 1 — Foundation\n\nSet up the project with:\n1. Next.js 15 (App Router) with TypeScript strict mode\n2. Tailwind CSS configured\n3. Supabase client initialized\n4. Basic layout with navigation\n5. Auth pages (signup, login)\n\nFollow all conventions from the Cursor Rules section above.\nStart by creating the project structure.`
    : `## Tugas Saat Ini: Fase 1 — Fondasi\n\nSetup proyek dengan:\n1. Next.js 15 (App Router) dengan TypeScript strict mode\n2. Tailwind CSS terkonfigurasi\n3. Supabase client diinisialisasi\n4. Layout dasar dengan navigasi\n5. Halaman auth (daftar, masuk)\n\nIkuti semua konvensi dari bagian Aturan Cursor di atas.\nMulai dengan membuat struktur proyek.`;
  md += "\n```\n\n";

  // Footer
  md += `---\n\n`;
  md += `*${isEn ? "Generated by Cursor Ready — From rough idea to Cursor-ready plan." : "Dihasilkan oleh Cursor Ready — Dari ide mentah ke rencana siap Cursor."}*  \n`;
  md += `*cursorready.dev*\n`;

  return md;
}

/**
 * Export a single step as Markdown
 */
export function exportStepAsMarkdown(content: string, stepName: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, `${stepName.toLowerCase().replace(/\s+/g, "-")}.md`);
}

/**
 * Export full project as a single Markdown file
 */
export function exportFullProject(stepContent: Record<number, string>, stepNames: string[]): void {
  const sections = Object.entries(stepContent)
    .map(([stepId, content]) => {
      const name = stepNames[Number(stepId)] || `Step ${stepId}`;
      return `\n\n---\n\n## ${name}\n\n${content}`;
    })
    .join("");

  const fullContent = `# Full Project Plan\n*Generated by Cursor Ready*\n${sections}`;
  const blob = new Blob([fullContent], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, "full-project-plan.md");
}
