/**
 * CURSOR READY — Export Utilities
 * Generates Cursor Pack ZIP and other export formats
 */

import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { Locale } from "./i18n";

export async function generateCursorPack(
  stepContent: Record<number, string>,
  locale: Locale
): Promise<void> {
  const zip = new JSZip();

  // PRD.md
  zip.file("PRD.md", stepContent[1] || generateDefaultPRD(locale));

  // schema.sql
  zip.file("schema.sql", stepContent[4] || generateDefaultSchema());

  // openapi.yaml
  zip.file("openapi.yaml", generateDefaultOpenAPI());

  // TASKS.md
  zip.file("TASKS.md", stepContent[6] || generateDefaultTasks(locale));

  // AGENTS.md (works across AI coding tools)
  zip.file("AGENTS.md", generateAgentsMD(locale));

  // CLAUDE.md (optional for Claude Code users)
  zip.file("CLAUDE.md", generateClaudeMD(locale));

  // .cursor/rules/
  const rulesFolder = zip.folder(".cursor/rules");
  if (rulesFolder) {
    rulesFolder.file("project-overview.mdc", generateProjectOverviewRule());
    rulesFolder.file("tech-stack.mdc", generateTechStackRule());
    rulesFolder.file("database-rules.mdc", generateDatabaseRules());
    rulesFolder.file("task-workflow.mdc", generateTaskWorkflowRule());
  }

  // prompts/
  const promptsFolder = zip.folder("prompts");
  if (promptsFolder) {
    promptsFolder.file("kickoff.md", stepContent[7] || generateKickoffPrompt(locale));
    promptsFolder.file("phase-1-setup.md", generatePhasePrompt(1, "Foundation & Setup", locale));
    promptsFolder.file("phase-2-features.md", generatePhasePrompt(2, "Core Features", locale));
    promptsFolder.file("phase-3-polish.md", generatePhasePrompt(3, "Polish & i18n", locale));
    promptsFolder.file("phase-4-launch.md", generatePhasePrompt(4, "Launch & Deploy", locale));
  }

  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, "cursor-pack.zip");
}

function generateDefaultPRD(locale: Locale): string {
  return locale === "en"
    ? `# Product Requirements Document\n\n## Overview\nYour project PRD goes here.\n\n## Goals\n- Define clear product goals\n- List user stories\n- Set success metrics\n`
    : `# Dokumen Kebutuhan Produk\n\n## Ringkasan\nPRD proyek Anda ada di sini.\n\n## Tujuan\n- Tentukan tujuan produk yang jelas\n- Daftar user stories\n- Tetapkan metrik kesuksesan\n`;
}

function generateDefaultSchema(): string {
  return `-- Database Schema\n-- Generated by Cursor Ready\n\nCREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n-- Add your tables here based on the architecture step\n`;
}

function generateDefaultOpenAPI(): string {
  return `openapi: 3.1.0
info:
  title: Project API
  version: 1.0.0
  description: API specification generated by Cursor Ready
servers:
  - url: https://api.example.com/v1
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
`;
}

function generateDefaultTasks(locale: Locale): string {
  return locale === "en"
    ? `# Task Breakdown\n\n## Phase 1: Foundation\n- [ ] Project setup\n- [ ] Database migrations\n- [ ] Auth flow\n\n## Phase 2: Core Features\n- [ ] Main feature implementation\n- [ ] API endpoints\n- [ ] UI components\n`
    : `# Rincian Tugas\n\n## Fase 1: Fondasi\n- [ ] Setup proyek\n- [ ] Migrasi database\n- [ ] Alur auth\n\n## Fase 2: Fitur Inti\n- [ ] Implementasi fitur utama\n- [ ] Endpoint API\n- [ ] Komponen UI\n`;
}

function generateAgentsMD(locale: Locale): string {
  return `# AGENTS.md
# Works with: Cursor, Claude Code, Lovable, Bolt, v0, and other AI coding tools

## Project Overview
This project was planned using Cursor Ready. Follow the files in this pack to build the application.

## File Guide
- \`PRD.md\` — Product requirements and user stories
- \`schema.sql\` — Database schema (run against your PostgreSQL instance)
- \`openapi.yaml\` — API specification
- \`TASKS.md\` — Phased task breakdown with estimates
- \`.cursor/rules/\` — Cursor-specific project rules
- \`prompts/\` — Phased coding prompts

## Workflow
1. Read PRD.md to understand the product
2. Run schema.sql to set up the database
3. Follow TASKS.md phases in order
4. Use prompts in \`prompts/\` for each phase
5. Reference .cursor/rules/ for conventions

## Conventions
- TypeScript strict mode
- No inline styles — use Tailwind CSS
- All functions need JSDoc comments
- Tests for critical paths
- Semantic HTML and WCAG AA accessibility
`;
}

function generateClaudeMD(locale: Locale): string {
  return `# CLAUDE.md
# Claude Code Configuration

## Context
This project was planned with Cursor Ready. Use the following files as context:
- PRD.md for product requirements
- TASKS.md for the phased build plan
- schema.sql for database structure

## Instructions
When working on this project:
1. Always read TASKS.md first to know which phase you're in
2. Follow the conventions in .cursor/rules/
3. Use TypeScript strict mode
4. Write tests for new functionality
5. Keep commits atomic and well-described

## Current Phase
Check TASKS.md for the current phase and tasks.
`;
}

function generateProjectOverviewRule(): string {
  return `---
description: Project overview and conventions
globs: **/*
alwaysApply: true
---

# Project Overview

## Stack
- Next.js 15 (App Router)
- TypeScript (strict mode)
- Tailwind CSS
- Supabase (auth, database, storage)
- Vercel AI SDK

## Conventions
- All components use PascalCase filenames
- API routes in /app/api/
- Shared types in /lib/types.ts
- No inline styles — Tailwind only
- Every function needs JSDoc comments
- Use Server Components by default
- Mark Client Components with "use client"

## Code Style
- Prefer const over let
- Use named exports for components
- Destructure props
- Handle errors explicitly
- No any types`;
}

function generateTechStackRule(): string {
  return `---
description: Technology stack and configuration rules
globs: **/*.{ts,tsx,js,jsx}
alwaysApply: false
---

# Tech Stack Rules

## Dependencies
- React 19 patterns (pass ref as prop, no forwardRef)
- TanStack Query for data fetching
- Zod for all validation
- lucide-react for icons

## Styling
- Tailwind CSS only (no CSS modules or styled-components)
- Sharp corners only (no border-radius)
- No gradients or soft shadows
- Use the design token system

## Database
- PostgreSQL via Supabase
- snake_case for all columns
- Always include created_at, updated_at
- Soft deletes via deleted_at
- UUID primary keys`;
}

function generateDatabaseRules(): string {
  return `---
description: Database and API rules
globs: **/*.{sql,ts}
alwaysApply: false
---

# Database & API Rules

## Schema Conventions
- UUID primary keys (uuid_generate_v4())
- snake_case column names
- TIMESTAMPTZ for all timestamps
- NOT NULL unless explicitly optional
- CHECK constraints for enums
- Foreign keys with ON DELETE CASCADE where appropriate

## Query Rules
- Always use parameterized queries
- Never SELECT * in production code
- Index foreign key columns
- Use EXPLAIN ANALYZE for slow queries

## API Rules
- RESTful endpoint naming
- Zod validation on all inputs
- Return consistent error shapes
- Paginate list endpoints
- Rate limit public endpoints`;
}

function generateTaskWorkflowRule(): string {
  return `---
description: Task workflow and development process
globs: **/*
alwaysApply: false
---

# Task Workflow

## Development Process
1. Read the current task from TASKS.md
2. Understand requirements from PRD.md
3. Implement the feature
4. Write tests
5. Update documentation
6. Mark task complete in TASKS.md

## Git Conventions
- Atomic commits (one logical change per commit)
- Conventional commit messages
- Branch per feature
- No force pushes to main

## Testing
- Unit tests for utility functions
- Integration tests for API routes
- E2E tests for critical user flows
- Minimum 80% coverage on new code`;
}

function generateKickoffPrompt(locale: Locale): string {
  return locale === "en"
    ? `# Kickoff Prompt for Cursor

You are building a new web application. Read the following files for full context:
- PRD.md — product requirements
- schema.sql — database schema  
- TASKS.md — phased task breakdown

## Current Task: Phase 1 — Foundation

Set up the project with:
1. Next.js 15 (App Router) with TypeScript strict mode
2. Tailwind CSS configured
3. Supabase client initialized
4. Basic layout with navigation
5. Auth pages (signup, login)

Follow all conventions in .cursor/rules/ files.
Start by creating the project structure.`
    : `# Prompt Awal untuk Cursor

Anda membangun aplikasi web baru. Baca file berikut untuk konteks lengkap:
- PRD.md — kebutuhan produk
- schema.sql — skema database
- TASKS.md — rincian tugas bertahap

## Tugas Saat Ini: Fase 1 — Fondasi

Setup proyek dengan:
1. Next.js 15 (App Router) dengan TypeScript strict mode
2. Tailwind CSS terkonfigurasi
3. Supabase client diinisialisasi
4. Layout dasar dengan navigasi
5. Halaman auth (daftar, masuk)

Ikuti semua konvensi di file .cursor/rules/.
Mulai dengan membuat struktur proyek.`;
}

function generatePhasePrompt(phase: number, title: string, locale: Locale): string {
  return locale === "en"
    ? `# Phase ${phase}: ${title}

Continue building the project. Read TASKS.md for the specific tasks in this phase.

## Instructions
1. Check which tasks are marked as pending in TASKS.md
2. Complete them in order
3. Follow all conventions from .cursor/rules/
4. Test each feature before moving to the next
5. Update TASKS.md as you complete tasks

## Reminders
- Use Server Components by default
- Validate all inputs with Zod
- Handle loading and error states
- Keep components small and focused`
    : `# Fase ${phase}: ${title}

Lanjutkan membangun proyek. Baca TASKS.md untuk tugas spesifik di fase ini.

## Instruksi
1. Periksa tugas yang masih pending di TASKS.md
2. Selesaikan secara berurutan
3. Ikuti semua konvensi dari .cursor/rules/
4. Test setiap fitur sebelum lanjut
5. Update TASKS.md saat tugas selesai

## Pengingat
- Gunakan Server Components secara default
- Validasi semua input dengan Zod
- Handle state loading dan error
- Jaga komponen tetap kecil dan fokus`;
}

/**
 * Export a single step as Markdown
 */
export function exportStepAsMarkdown(content: string, stepName: string): void {
  const blob = new Blob([content], { type: "text/markdown" });
  saveAs(blob, `${stepName.toLowerCase().replace(/\s+/g, "-")}.md`);
}

/**
 * Export full project as a single Markdown file
 */
export function exportFullProject(stepContent: Record<number, string>, stepNames: string[]): void {
  const sections = Object.entries(stepContent)
    .map(([stepId, content]) => {
      const name = stepNames[Number(stepId)] || `Step ${stepId}`;
      return `\n\n---\n\n# ${name}\n\n${content}`;
    })
    .join("");

  const fullContent = `# Full Project Plan\n*Generated by Cursor Ready*\n${sections}`;
  const blob = new Blob([fullContent], { type: "text/markdown" });
  saveAs(blob, "full-project-plan.md");
}
